// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_space_surgeon = "CgkIusy6mqADEAIQBQ"; // <GPGSID>
        public const string achievement_all_cards_on_the_table = "CgkIusy6mqADEAIQCA"; // <GPGSID>
        public const string achievement_imma_fire_mah_laserr = "CgkIusy6mqADEAIQBA"; // <GPGSID>
        public const string achievement_moooooooo = "CgkIusy6mqADEAIQCQ"; // <GPGSID>
        public const string achievement_meatballed = "CgkIusy6mqADEAIQAg"; // <GPGSID>
        public const string achievement_see_you_space_cowboy = "CgkIusy6mqADEAIQAw"; // <GPGSID>
        public const string achievement_battleships = "CgkIusy6mqADEAIQBw"; // <GPGSID>
        public const string achievement_gg_ez = "CgkIusy6mqADEAIQAA"; // <GPGSID>
        public const string achievement_space_sniper = "CgkIusy6mqADEAIQBg"; // <GPGSID>

}

